// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4761.MotorSpinBot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeftFront;
    public static SpeedController driveTrainLeftRear;
    public static SpeedController driveTrainRightFront;
    public static SpeedController driveTrainRIghtRear;
    public static RobotDrive driveTrainRoboDrive;
    public static Gyro driveTrainGyro;
    public static AnalogInput driveTrainDistanceSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftFront = new Talon(1);
        LiveWindow.addActuator("Drive Train", "Left Front", (Talon) driveTrainLeftFront);
        
        driveTrainLeftRear = new Talon(2);
        LiveWindow.addActuator("Drive Train", "Left Rear", (Talon) driveTrainLeftRear);
        
        driveTrainRightFront = new Talon(3);
        LiveWindow.addActuator("Drive Train", "Right Front", (Talon) driveTrainRightFront);
        
        driveTrainRIghtRear = new Talon(4);
        LiveWindow.addActuator("Drive Train", "RIght Rear", (Talon) driveTrainRIghtRear);
        
        driveTrainRoboDrive = new RobotDrive(driveTrainLeftFront, driveTrainLeftRear,
              driveTrainRightFront, driveTrainRIghtRear);
        
        driveTrainRoboDrive.setSafetyEnabled(true);
        driveTrainRoboDrive.setExpiration(0.1);
        driveTrainRoboDrive.setSensitivity(0.5);
        driveTrainRoboDrive.setMaxOutput(1.0);

        driveTrainGyro = new Gyro(0);
        LiveWindow.addSensor("Drive Train", "Gyro", driveTrainGyro);
        driveTrainGyro.setSensitivity(0.007);
        driveTrainDistanceSensor = new AnalogInput(2);
        LiveWindow.addSensor("Drive Train", "Distance Sensor", driveTrainDistanceSensor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
